import React from 'react'
import { useState } from 'react';
import './App.css'
import Header from './Header';
import Select from './Select';

function App() {
  const [product, setProduct] = useState(
    {
      "id": 6657998749858,
      "title": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE",
      "handle": "gpu-amd-series-radeon-r9-270-x",
      "description": "All GPU Amd series Radeon R9 270X",
      "published_at": "2021-04-02T13:44:41-07:00",
      "created_at": "2021-04-02T08:18:58-07:00",
      "vendor": "knightowllabs",
      "type": "GPU",
      "tags": [
        "amd",
        "gpu"
      ],
      "price": 9900,
      "price_min": 9900,
      "price_max": 9900,
      "available": true,
      "price_varies": false,
      "compare_at_price": null,
      "compare_at_price_min": 0,
      "compare_at_price_max": 0,
      "compare_at_price_varies": false,
      "variants": [
        {
          "id": 39593804628130,
          "title": "RADEON R9 270X \/ ASUS \/ ASUS R9 270X DIRECTCU II",
          "option1": "RADEON R9 270X",
          "option2": "ASUS",
          "option3": "ASUS R9 270X DIRECTCU II",
          "sku": null,
          "requires_shipping": true,
          "taxable": true,
          "featured_image": null,
          "available": true,
          "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ ASUS \/ ASUS R9 270X DIRECTCU II",
          "public_title": "RADEON R9 270X \/ ASUS \/ ASUS R9 270X DIRECTCU II",
          "options": [
            "RADEON R9 270X",
            "ASUS",
            "ASUS R9 270X DIRECTCU II"
          ],
          "price": 9900,
          "weight": 0,
          "compare_at_price": null,
          "inventory_management": "shopify",
          "barcode": null,
          "requires_selling_plan": false,
          "selling_plan_allocations": []
        },
        {
          "id": 39593804660898,
          "title": "RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X'14SERIES",
          "option1": "RADEON R9 270X",
          "option2": "CLUB3D",
          "option3": "CLUB 3D R9 270X'14SERIES",
          "sku": null,
          "requires_shipping": true,
          "taxable": true,
          "featured_image": null,
          "available": true,
          "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X'14SERIES",
          "public_title": "RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X'14SERIES",
          "options": [
            "RADEON R9 270X",
            "CLUB3D",
            "CLUB 3D R9 270X'14SERIES"
          ],
          "price": 9900,
          "weight": 0,
          "compare_at_price": null,
          "inventory_management": "shopify",
          "barcode": null,
          "requires_selling_plan": false,
          "selling_plan_allocations": []
        },
        {
            "id": 39593804693666,
            "title": "RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X ROYALQUEEN",
            "option1": "RADEON R9 270X",
            "option2": "CLUB3D",
            "option3": "CLUB 3D R9 270X ROYALQUEEN",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X ROYALQUEEN",
            "public_title": "RADEON R9 270X \/ CLUB3D \/ CLUB 3D R9 270X ROYALQUEEN",
            "options": [
                "RADEON R9 270X",
                "CLUB3D",
                "CLUB 3D R9 270X ROYALQUEEN"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804726434,
            "title": "RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC",
            "option1": "RADEON R9 270X",
            "option2": "GIGABYTE",
            "option3": "GIGABYTE R9 270X WINDFORCE 3X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC",
            "public_title": "RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC",
            "options": [
                "RADEON R9 270X",
                "GIGABYTE",
                "GIGABYTE R9 270X WINDFORCE 3X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804759202,
            "title": "RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC REV. 2",
            "option1": "RADEON R9 270X",
            "option2": "GIGABYTE",
            "option3": "GIGABYTE R9 270X WINDFORCE 3X OC REV. 2",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC REV. 2",
            "public_title": "RADEON R9 270X \/ GIGABYTE \/ GIGABYTE R9 270X WINDFORCE 3X OC REV. 2",
            "options": [
                "RADEON R9 270X",
                "GIGABYTE",
                "GIGABYTE R9 270X WINDFORCE 3X OC REV. 2"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804791970,
            "title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ BOOST CLOCK",
            "option1": "RADEON R9 270X",
            "option2": "HIS",
            "option3": "HIS R9 270X ICEQ BOOST CLOCK",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ BOOST CLOCK",
            "public_title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ BOOST CLOCK",
            "options": [
                "RADEON R9 270X",
                "HIS",
                "HIS R9 270X ICEQ BOOST CLOCK"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804824738,
            "title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 BOOST CLOCK",
            "option1": "RADEON R9 270X",
            "option2": "HIS",
            "option3": "HIS R9 270X ICEQ X2 BOOST CLOCK",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 BOOST CLOCK",
            "public_title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 BOOST CLOCK",
            "options": [
                "RADEON R9 270X",
                "HIS",
                "HIS R9 270X ICEQ X2 BOOST CLOCK"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804857506,
            "title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 TURBO BOOST CLOCK",
            "option1": "RADEON R9 270X",
            "option2": "HIS",
            "option3": "HIS R9 270X ICEQ X2 TURBO BOOST CLOCK",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 TURBO BOOST CLOCK",
            "public_title": "RADEON R9 270X \/ HIS \/ HIS R9 270X ICEQ X2 TURBO BOOST CLOCK",
            "options": [
                "RADEON R9 270X",
                "HIS",
                "HIS R9 270X ICEQ X2 TURBO BOOST CLOCK"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804890274,
            "title": "RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING OC",
            "option1": "RADEON R9 270X",
            "option2": "MSI",
            "option3": "MSI R9 270X GAMING OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING OC",
            "public_title": "RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING OC",
            "options": [
                "RADEON R9 270X",
                "MSI",
                "MSI R9 270X GAMING OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804923042,
            "title": "RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING ITX",
            "option1": "RADEON R9 270X",
            "option2": "MSI",
            "option3": "MSI R9 270X GAMING ITX",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING ITX",
            "public_title": "RADEON R9 270X \/ MSI \/ MSI R9 270X GAMING ITX",
            "options": [
                "RADEON R9 270X",
                "MSI",
                "MSI R9 270X GAMING ITX"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804955810,
            "title": "RADEON R9 270X \/ MSI \/ MSI R9 270X HAWK",
            "option1": "RADEON R9 270X",
            "option2": "MSI",
            "option3": "MSI R9 270X HAWK",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ MSI \/ MSI R9 270X HAWK",
            "public_title": "RADEON R9 270X \/ MSI \/ MSI R9 270X HAWK",
            "options": [
                "RADEON R9 270X",
                "MSI",
                "MSI R9 270X HAWK"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593804988578,
            "title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR R9 270X OC",
            "option1": "RADEON R9 270X",
            "option2": "POWERCOLOR",
            "option3": "POWERCOLOR R9 270X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR R9 270X OC",
            "public_title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR R9 270X OC",
            "options": [
                "RADEON R9 270X",
                "POWERCOLOR",
                "POWERCOLOR R9 270X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805021346,
            "title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR PCS+ R9 270X",
            "option1": "RADEON R9 270X",
            "option2": "POWERCOLOR",
            "option3": "POWERCOLOR PCS+ R9 270X",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR PCS+ R9 270X",
            "public_title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR PCS+ R9 270X",
            "options": [
                "RADEON R9 270X",
                "POWERCOLOR",
                "POWERCOLOR PCS+ R9 270X"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805054114,
            "title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR DEVIL R9 270X",
            "option1": "RADEON R9 270X",
            "option2": "POWERCOLOR",
            "option3": "POWERCOLOR DEVIL R9 270X",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR DEVIL R9 270X",
            "public_title": "RADEON R9 270X \/ POWERCOLOR \/ POWERCOLOR DEVIL R9 270X",
            "options": [
                "RADEON R9 270X",
                "POWERCOLOR",
                "POWERCOLOR DEVIL R9 270X"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805086882,
            "title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE DUAL-X R9 270X OC",
            "option1": "RADEON R9 270X",
            "option2": "SAPPHIRE",
            "option3": "SAPPHIRE DUAL-X R9 270X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE DUAL-X R9 270X OC",
            "public_title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE DUAL-X R9 270X OC",
            "options": [
                "RADEON R9 270X",
                "SAPPHIRE",
                "SAPPHIRE DUAL-X R9 270X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805119650,
            "title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE TOXIC R9 270X OC",
            "option1": "RADEON R9 270X",
            "option2": "SAPPHIRE",
            "option3": "SAPPHIRE TOXIC R9 270X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE TOXIC R9 270X OC",
            "public_title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE TOXIC R9 270X OC",
            "options": [
                "RADEON R9 270X",
                "SAPPHIRE",
                "SAPPHIRE TOXIC R9 270X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805152418,
            "title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE VAPOR-X R9 270X OC",
            "option1": "RADEON R9 270X",
            "option2": "SAPPHIRE",
            "option3": "SAPPHIRE VAPOR-X R9 270X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE VAPOR-X R9 270X OC",
            "public_title": "RADEON R9 270X \/ SAPPHIRE \/ SAPPHIRE VAPOR-X R9 270X OC",
            "options": [
                "RADEON R9 270X",
                "SAPPHIRE",
                "SAPPHIRE VAPOR-X R9 270X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805185186,
            "title": "RADEON R9 270X \/ VISIONTEK \/ VISIONTEK R9 270X OC",
            "option1": "RADEON R9 270X",
            "option2": "VISIONTEK",
            "option3": "VISIONTEK R9 270X OC",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ VISIONTEK \/ VISIONTEK R9 270X OC",
            "public_title": "RADEON R9 270X \/ VISIONTEK \/ VISIONTEK R9 270X OC",
            "options": [
                "RADEON R9 270X",
                "VISIONTEK",
                "VISIONTEK R9 270X OC"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805217954,
            "title": "RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION",
            "option1": "RADEON R9 270X",
            "option2": "VTX3D",
            "option3": "VTX3D R9 270X X-EDITION",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION",
            "public_title": "RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION",
            "options": [
                "RADEON R9 270X",
                "VTX3D",
                "VTX3D R9 270X X-EDITION"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805250722,
            "title": "RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION V2",
            "option1": "RADEON R9 270X",
            "option2": "VTX3D",
            "option3": "VTX3D R9 270X X-EDITION V2",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION V2",
            "public_title": "RADEON R9 270X \/ VTX3D \/ VTX3D R9 270X X-EDITION V2",
            "options": [
                "RADEON R9 270X",
                "VTX3D",
                "VTX3D R9 270X X-EDITION V2"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805283490,
            "title": "RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X",
            "option1": "RADEON R9 270X",
            "option2": "XFX",
            "option3": "XFX DOUBLE D R9 270X",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X",
            "public_title": "RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X",
            "options": [
                "RADEON R9 270X",
                "XFX",
                "XFX DOUBLE D R9 270X"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805316258,
            "title": "RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X BLACK EDITION",
            "option1": "RADEON R9 270X",
            "option2": "XFX",
            "option3": "XFX DOUBLE D R9 270X BLACK EDITION",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X BLACK EDITION",
            "public_title": "RADEON R9 270X \/ XFX \/ XFX DOUBLE D R9 270X BLACK EDITION",
            "options": [
                "RADEON R9 270X",
                "XFX",
                "XFX DOUBLE D R9 270X BLACK EDITION"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        },
        {
            "id": 39593805349026,
            "title": "RADEON R9 270X \/ XFX \/ XFX R9 270X BESTBUY EXCLUSIVE",
            "option1": "RADEON R9 270X",
            "option2": "XFX",
            "option3": "XFX R9 270X BESTBUY EXCLUSIVE",
            "sku": null,
            "requires_shipping": true,
            "taxable": true,
            "featured_image": null,
            "available": true,
            "name": "GPU Amd series Radeon R9 270X RGB GPU BACKPLATE - RADEON R9 270X \/ XFX \/ XFX R9 270X BESTBUY EXCLUSIVE",
            "public_title": "RADEON R9 270X \/ XFX \/ XFX R9 270X BESTBUY EXCLUSIVE",
            "options": [
                "RADEON R9 270X",
                "XFX",
                "XFX R9 270X BESTBUY EXCLUSIVE"
            ],
            "price": 9900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_management": "shopify",
            "barcode": null,
            "requires_selling_plan": false,
            "selling_plan_allocations": []
        }
      ]
    }
  )
  const list = () => {
    for (const i = 0; i < product.variants.length; i++) {
      return <p>{product.variants[i]}</p>
    }
  }

  return (
    <div className="App">
      <Header />
      {
        product.variants.map((item, value) => (
          <p key={item.id}>{item.title}</p>
        ))
      }
      
    </div>
  );
}

export default App;